# Generated by Django 6.0 on 2026-01-08 09:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('last_date', models.DateField()),
                ('posted_date', models.DateField(default=django.utils.timezone.now)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_app.employer')),
            ],
        ),
    ]
