# Generated by Django 6.0 on 2026-01-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0002_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='posted_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
