# Generated by Django 6.0 on 2026-01-08 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0003_job_status_alter_job_posted_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Viewed', 'Viewed'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Applied', max_length=20)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_app.job')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_app.seeker')),
            ],
            options={
                'unique_together': {('seeker', 'job')},
            },
        ),
    ]
