# Generated by Django 6.0 on 2026-01-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0005_job_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeker',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seeker',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='seeker_profiles/'),
        ),
    ]
