# Generated by Django 6.0 on 2026-01-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0006_seeker_address_seeker_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
