# Generated by Django 6.0 on 2026-01-09 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0008_seekernotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeekerNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_company', models.CharField(blank=True, max_length=100)),
                ('preferred_title', models.CharField(blank=True, max_length=100)),
                ('seeker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='job_app.seeker')),
            ],
        ),
    ]
