# Generated by Django 6.0 on 2026-01-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0009_seekernotificationpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='admin_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='admin_seen',
            field=models.BooleanField(default=False),
        ),
    ]
