# Generated by Django 6.0 on 2026-01-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0010_application_admin_seen_job_admin_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Viewed', 'Viewed'), ('Profile Visited', 'Profile Visited'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Applied', max_length=20),
        ),
    ]
